-- +goose Up
-- End-to-end idempotency for the offline chat queue, mirroring the SOS pattern
-- in migration 075.
--
-- Both the pilgrim and leader apps queue chat sends while offline and replay
-- them on reconnect. A send whose response was lost after the row committed is
-- replayed, and the message is posted twice. The queue also retries per item,
-- so one lost response can produce several copies.
--
-- Scoped per sender rather than globally: two people may legitimately send the
-- same text, and a key generated by one client must not collide with another's.
-- Empty key means no dedup, so callers that predate this keep working.
ALTER TABLE chat_messages
  ADD COLUMN IF NOT EXISTS idempotency_key TEXT NOT NULL DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_messages_idempotency_user
  ON chat_messages (sender_user_id, idempotency_key)
  WHERE idempotency_key <> '' AND sender_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_messages_idempotency_pilgrim
  ON chat_messages (sender_pilgrim_id, idempotency_key)
  WHERE idempotency_key <> '' AND sender_pilgrim_id IS NOT NULL;

-- +goose Down
DROP INDEX IF EXISTS idx_chat_messages_idempotency_pilgrim;
DROP INDEX IF EXISTS idx_chat_messages_idempotency_user;
ALTER TABLE chat_messages DROP COLUMN IF EXISTS idempotency_key;
