"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { IconArrowBack, IconBed, IconDownload, IconPlus } from "@tabler/icons-react";
import { Hotel, Room, RoomManifest } from "@hajj-saas/proto-gen/hajj/v1/accommodation_pb";
import { accommodationClient } from "@/lib/rpc";
import { exportCSV } from "@/lib/csv";
import BulkRoomDialog from "./BulkRoomDialog";
import RoomAllocationPanel from "./RoomAllocationPanel";
import RoomFormDialog from "./RoomFormDialog";

export default function AccommodationRoomsDashboard({ hotelId }: { hotelId: string }) {
  const [hotel, setHotel] = useState<Hotel>(); const [rooms, setRooms] = useState<Room[]>([]); const [manifests, setManifests] = useState<Record<string, RoomManifest>>({}); const [selected, setSelected] = useState<Room | null>(null); const [roomOpen, setRoomOpen] = useState(false); const [bulkOpen, setBulkOpen] = useState(false); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const refresh = async () => { setLoading(true); try { const [hotelValue, roomsResponse] = await Promise.all([accommodationClient.getHotel({ hotelId }), accommodationClient.listRooms({ hotelId })]); setHotel(hotelValue); setRooms(roomsResponse.rooms); const pairs = await Promise.all(roomsResponse.rooms.map(async (room) => [room.id, await accommodationClient.getRoomManifest({ roomId: room.id })] as const)); setManifests(Object.fromEntries(pairs)); } catch { setNotice("Gagal memuat data kamar hotel."); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, [hotelId]);
  const allocatedPilgrimIds = useMemo(() => new Set(Object.values(manifests).flatMap((manifest) => manifest.pilgrims.map((pilgrim) => pilgrim.id))), [manifests]);
  const byFloor = useMemo(() => rooms.reduce<Record<string, Room[]>>((groups, room) => { const floor = room.floor ? `Lantai ${room.floor}` : "Lantai belum ditentukan"; (groups[floor] ??= []).push(room); return groups; }, {}), [rooms]);
  function exportRooms() {
    const headers = ["No. Kamar", "Lantai", "Tipe", "Jenis Kelamin", "Kapasitas", "Terisi", "Penghuni"];
    const rows = rooms.map((room) => { const manifest = manifests[room.id]; const occupied = room.capacity - (manifest?.availableCapacity ?? room.capacity); return [room.roomNumber, room.floor ? String(room.floor) : "-", room.roomType, room.gender, String(room.capacity), String(occupied), (manifest?.pilgrims ?? []).map((p) => `${p.fullName} (${p.passportNumber})`).join("; ")]; });
    exportCSV(`${hotel?.name ?? "hotel"}-rooms.csv`, headers, rows);
  }
  return <main style={page}><Link href="/dashboard/accommodation" style={back}><IconArrowBack size={18} />Kembali ke akomodasi</Link><header style={header}><div><p style={eyebrow}>HOTEL / DATA KAMAR</p><h1 style={title}>{hotel?.name ?? "Kamar hotel"}</h1>{hotel && <span style={cityBadge}>{hotel.city}</span>}</div><div style={actions}>{!!rooms.length && <button onClick={exportRooms} style={ghost}><IconDownload size={18} />Ekspor CSV</button>}<button onClick={() => setBulkOpen(true)} style={gold}><IconBed size={18} />Tambah Kamar Massal</button><button onClick={() => setRoomOpen(true)} style={emerald}><IconPlus size={18} />Tambah Kamar</button></div></header><div className="gold-divider" />{notice && <p role="status" style={{ color: "var(--color-gold-800)" }}>{notice}</p>}{loading ? <section style={empty}>Memuat data kamar...</section> : rooms.length ? <div style={{ display: "grid", gap: 32 }}>{Object.entries(byFloor).map(([floor, values]) => <section key={floor}><h2 style={{ margin: "0 0 12px" }}>{floor}</h2><div style={roomGrid}>{values.map((room) => <RoomCard key={room.id} room={room} manifest={manifests[room.id]} onClick={() => setSelected(room)} />)}</div></section>)}</div> : <section style={empty}><IconBed size={48} color="var(--color-warm-400)" /><h2 style={{ margin: 0 }}>Belum ada kamar</h2><p style={{ margin: 0, color: "var(--color-warm-500)" }}>Tambahkan kamar satu per satu atau buat satu lantai penuh sekaligus.</p><button onClick={() => setRoomOpen(true)} style={gold}><IconPlus size={18} />Tambah Kamar</button></section>}<RoomFormDialog open={roomOpen} hotelId={hotelId} onClose={() => setRoomOpen(false)} onSaved={() => { setNotice("Kamar berhasil ditambahkan"); void refresh(); }} /><BulkRoomDialog open={bulkOpen} hotelId={hotelId} onClose={() => setBulkOpen(false)} onSaved={(count) => { setNotice(`${count} kamar berhasil dibuat`); void refresh(); }} /><RoomAllocationPanel open={!!selected} room={selected} seasonId={hotel?.seasonId ?? ""} allocatedPilgrimIds={allocatedPilgrimIds} onClose={() => setSelected(null)} onChanged={() => void refresh()} /></main>;
}
function RoomCard({ room, manifest, onClick }: { room: Room; manifest?: RoomManifest; onClick: () => void }) { const occupied = room.capacity - (manifest?.availableCapacity ?? room.capacity); const full = occupied >= room.capacity; const people = manifest?.pilgrims ?? []; return <button onClick={onClick} style={{ ...roomCard, background: full ? "var(--color-gold-50)" : occupied ? "var(--color-emerald-50)" : "var(--color-cream-200)" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><strong style={{ fontSize: 20 }}>Kamar {room.roomNumber}</strong><span style={genderBadge}>{label(room.gender)}</span></div><span style={typeBadge}>{ROOM_TYPE_LABEL[room.roomType] ?? label(room.roomType)}</span><div style={barTrack}><div style={{ ...barFill, width: `${Math.min(100, room.capacity ? occupied / room.capacity * 100 : 0)}%` }} /></div><span style={{ color: "var(--color-warm-500)", fontSize: 13 }}>{occupied}/{room.capacity} terisi</span>{people.length ? <div style={names}>{people.map((pilgrim) => <span key={pilgrim.id}>{pilgrim.fullName}</span>)}</div> : <span style={{ color: "var(--color-warm-400)", fontSize: 13 }}>Belum ada jamaah</span>}</button>; }
function label(value: string) { return value ? value.charAt(0).toUpperCase() + value.slice(1) : "-"; }
const ROOM_TYPE_LABEL: Record<string, string> = { single: "Single", double: "Double", triple: "Triple", quad: "Quadruple", quadruple: "Quadruple" };
const page: React.CSSProperties = { maxWidth: 1400, margin: "0 auto", padding: "32px 24px" }; const back: React.CSSProperties = { minHeight: 48, display: "inline-flex", alignItems: "center", gap: 8, color: "var(--color-gold-800)", textDecoration: "none", marginBottom: 12 }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 24, flexWrap: "wrap" }; const actions: React.CSSProperties = { display: "flex", gap: 10, flexWrap: "wrap" }; const eyebrow: React.CSSProperties = { color: "var(--color-gold-800)", fontSize: 11, fontWeight: 700, letterSpacing: ".08em", margin: "4px 0 8px" }; const title: React.CSSProperties = { fontSize: "clamp(32px,5vw,48px)", fontWeight: 500, margin: 0 }; const cityBadge: React.CSSProperties = { display: "inline-flex", marginTop: 10, padding: "5px 10px", borderRadius: 99, background: "var(--color-emerald-50)", color: "var(--color-emerald-900)", fontSize: 12, textTransform: "capitalize" }; const emerald: React.CSSProperties = { minHeight: 48, border: 0, borderRadius: 8, padding: "0 18px", display: "inline-flex", gap: 8, alignItems: "center", background: "var(--color-emerald-900)", color: "var(--color-cream-100)", fontWeight: 700 }; const gold: React.CSSProperties = { ...emerald, background: "var(--color-gold-500)", color: "var(--color-warm-900)" }; const ghost: React.CSSProperties = { minHeight: 48, border: "1px solid var(--color-cream-500)", borderRadius: 8, padding: "0 18px", display: "inline-flex", gap: 8, alignItems: "center", background: "transparent", color: "var(--color-warm-700)", fontWeight: 700 }; const roomGrid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(230px, 1fr))", gap: 16 }; const roomCard: React.CSSProperties = { minHeight: 196, border: "1px solid var(--color-cream-400)", borderRadius: 12, padding: 16, textAlign: "start", color: "var(--color-warm-900)", display: "grid", alignContent: "start", gap: 10, cursor: "pointer" }; const genderBadge: React.CSSProperties = { alignSelf: "start", padding: "4px 8px", borderRadius: 99, background: "var(white)", color: "var(--color-warm-500)", fontSize: 12 }; const typeBadge: React.CSSProperties = { color: "var(--color-gold-800)", fontSize: 13, fontWeight: 700 }; const barTrack: React.CSSProperties = { height: 8, overflow: "hidden", borderRadius: 99, background: "var(--color-emerald-200)" }; const barFill: React.CSSProperties = { height: "100%", background: "var(--color-emerald-900)" }; const names: React.CSSProperties = { display: "grid", gap: 2, color: "var(--color-warm-500)", fontSize: 12 }; const empty: React.CSSProperties = { minHeight: 280, display: "grid", placeItems: "center", alignContent: "center", gap: 12, textAlign: "center", padding: 24, border: "1px dashed var(--color-cream-400)", borderRadius: 12, background: "var(--color-cream-100)" };
