"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { IconArrowBack, IconBed, IconDownload, IconPlus } from "@tabler/icons-react";
import { Hotel, Room, RoomManifest } from "@hajj-saas/proto-gen/hajj/v1/accommodation_pb";
import { accommodationClient } from "@/lib/rpc";
import { exportCSV } from "@/lib/csv";
import BulkRoomDialog from "./BulkRoomDialog";
import RoomAllocationPanel from "./RoomAllocationPanel";
import RoomFormDialog from "./RoomFormDialog";
import { StatCard } from "@/components/ui/StatCard";

export default function AccommodationRoomsDashboard({ hotelId }: { hotelId: string }) {
  const [hotel, setHotel] = useState<Hotel>(); const [rooms, setRooms] = useState<Room[]>([]); const [manifests, setManifests] = useState<Record<string, RoomManifest>>({}); const [selected, setSelected] = useState<Room | null>(null); const [roomOpen, setRoomOpen] = useState(false); const [bulkOpen, setBulkOpen] = useState(false); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [allocatedPilgrimIds, setAllocatedPilgrimIds] = useState<Set<string>>(new Set());
  const refresh = useCallback(async () => { setLoading(true); setNotice(""); try { const [hotelValue, roomsResponse] = await Promise.all([accommodationClient.getHotel({ hotelId }), accommodationClient.listRooms({ hotelId })]); setHotel(hotelValue); setRooms(roomsResponse.rooms); const pairs = await Promise.all(roomsResponse.rooms.map(async (room) => [room.id, await accommodationClient.getRoomManifest({ roomId: room.id })] as const)); setManifests(Object.fromEntries(pairs));
    // A pilgrim can hold one room PER HOTEL (Makkah + Madinah are both
    // valid at once) — so "already has a room" only excludes them here if
    // that room is in THIS hotel; being housed elsewhere doesn't disqualify
    // them from also getting a room in this one.
    if (hotelValue.seasonId) { const assignments = await accommodationClient.listPilgrimRoomAssignments({ seasonId: hotelValue.seasonId }); setAllocatedPilgrimIds(new Set(assignments.assignments.filter((a) => a.hotelId === hotelId).map((a) => a.pilgrimId))); }
  } catch { setNotice("Gagal memuat data kamar hotel."); } finally { setLoading(false); } }, [hotelId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const byFloor = useMemo(() => rooms.reduce<Record<string, Room[]>>((groups, room) => { const floor = room.floor ? `Lantai ${room.floor}` : "Lantai belum ditentukan"; (groups[floor] ??= []).push(room); return groups; }, {}), [rooms]);
  const metrics = useMemo(() => rooms.reduce((result, room) => { const available = manifests[room.id]?.availableCapacity ?? room.capacity; const occupied = Math.max(0, room.capacity - available); result.capacity += room.capacity; result.occupied += occupied; if (occupied >= room.capacity) result.full += 1; return result; }, { capacity: 0, occupied: 0, full: 0 }), [manifests, rooms]);
  function exportRooms() {
    const headers = ["No. Kamar", "Lantai", "Tipe", "Jenis Kelamin", "Kapasitas", "Terisi", "Penghuni"];
    const rows = rooms.map((room) => { const manifest = manifests[room.id]; const occupied = room.capacity - (manifest?.availableCapacity ?? room.capacity); return [room.roomNumber, room.floor ? String(room.floor) : "-", room.roomType, room.gender, String(room.capacity), String(occupied), (manifest?.pilgrims ?? []).map((p) => `${p.fullName} (${p.passportNumber})`).join("; ")]; });
    exportCSV(`${hotel?.name ?? "hotel"}-rooms.csv`, headers, rows);
  }
  return <main style={page}><Link href="/dashboard/accommodation" style={back}><IconArrowBack size={18} />Kembali ke akomodasi</Link><header style={header}><div><p style={eyebrow}>HOTEL / DATA KAMAR</p><h1 style={title}>{hotel?.name ?? "Kamar hotel"}</h1><p className="accommodation-room-page__subtitle">{rooms.length} kamar · {metrics.occupied}/{metrics.capacity} tempat tidur terisi{hotel ? ` · ${hotel.city}` : ""}</p></div><div style={actions}>{!!rooms.length && <button onClick={exportRooms} style={ghost}><IconDownload size={18} />Ekspor CSV</button>}<button onClick={() => setBulkOpen(true)} style={gold}><IconBed size={18} />Tambah Kamar Massal</button><button onClick={() => setRoomOpen(true)} style={emerald}><IconPlus size={18} />Tambah Kamar</button></div></header><div className="gold-divider" />{!loading && rooms.length > 0 && <section className="accommodation-room-stats" aria-label="Ringkasan okupansi"><StatCard label="Kamar tersedia" value={rooms.length} unit="kamar" tone="brand" /><StatCard label="Tempat tidur terisi" value={metrics.occupied} unit={`dari ${metrics.capacity}`} tone="success" /><StatCard label="Kamar penuh" value={metrics.full} unit="kamar" tone={metrics.full ? "warning" : "neutral"} /></section>}{notice && <p role="alert" className="accommodation-room-page__notice">{notice}</p>}{loading ? <section style={empty}>Memuat data kamar...</section> : rooms.length ? <div style={{ display: "grid", gap: 32 }}>{Object.entries(byFloor).map(([floor, values]) => <section key={floor} aria-labelledby={`floor-${floor.replaceAll(" ", "-")}`}><h2 id={`floor-${floor.replaceAll(" ", "-")}`} style={{ margin: "0 0 12px" }}>{floor}</h2><div style={roomGrid}>{values.map((room) => <RoomCard key={room.id} room={room} manifest={manifests[room.id]} onClick={() => setSelected(room)} />)}</div></section>)}</div> : <section style={empty}><IconBed size={48} color="var(--color-warm-400)" /><h2 style={{ margin: 0 }}>Belum ada kamar</h2><p style={{ margin: 0, color: "var(--color-warm-500)" }}>Tambahkan kamar satu per satu atau buat satu lantai penuh sekaligus.</p><button onClick={() => setRoomOpen(true)} style={gold}><IconPlus size={18} />Tambah Kamar</button></section>}<RoomFormDialog open={roomOpen} hotelId={hotelId} onClose={() => setRoomOpen(false)} onSaved={() => { void refresh().then(() => setNotice("Kamar berhasil ditambahkan")); }} /><BulkRoomDialog open={bulkOpen} hotelId={hotelId} onClose={() => setBulkOpen(false)} onSaved={(count) => { void refresh().then(() => setNotice(`${count} kamar berhasil dibuat`)); }} /><RoomAllocationPanel open={!!selected} room={selected} seasonId={hotel?.seasonId ?? ""} allocatedPilgrimIds={allocatedPilgrimIds} onClose={() => setSelected(null)} onChanged={() => void refresh()} /></main>;
}
function RoomCard({ room, manifest, onClick }: { room: Room; manifest?: RoomManifest; onClick: () => void }) { const occupied = Math.max(0, room.capacity - (manifest?.availableCapacity ?? room.capacity)); const full = occupied >= room.capacity; const people = manifest?.pilgrims ?? []; const hiddenOccupants = Math.max(0, occupied - people.length); const tone = full ? "full" : occupied ? "occupied" : "empty"; return <button type="button" onClick={onClick} className={`accommodation-room-card accommodation-room-card--${tone}`} aria-label={`Kelola kamar ${room.roomNumber}, ${occupied} dari ${room.capacity} tempat tidur terisi`}><div className="accommodation-room-card__header"><strong>Kamar {room.roomNumber}</strong><span>{label(room.gender)}</span></div><span className="accommodation-room-card__type">{ROOM_TYPE_LABEL[room.roomType] ?? label(room.roomType)}</span><div className="accommodation-room-card__track" aria-hidden="true"><span style={{ width: `${Math.min(100, room.capacity ? occupied / room.capacity * 100 : 0)}%` }} /></div><span className="accommodation-room-card__occupancy">{occupied}/{room.capacity} tempat tidur terisi</span>{people.length ? <div className="accommodation-room-card__names">{people.slice(0, 3).map((pilgrim) => <span key={pilgrim.id}>{pilgrim.fullName}</span>)}{people.length > 3 && <span>+{people.length - 3} jamaah cabang Anda</span>}{hiddenOccupants > 0 && <span>+{hiddenOccupants} jamaah cabang lain</span>}</div> : <span className="accommodation-room-card__empty">{hiddenOccupants ? `${hiddenOccupants} tempat tidur digunakan cabang lain` : "Belum ada jamaah dari cabang Anda"}</span>}</button>; }
function label(value: string) { return value ? value.charAt(0).toUpperCase() + value.slice(1) : "-"; }
const ROOM_TYPE_LABEL: Record<string, string> = { single: "Single", double: "Double", triple: "Triple", quad: "Quadruple", quadruple: "Quadruple" };
const page: React.CSSProperties = { maxWidth: 1400, margin: "0 auto", padding: "32px 24px" }; const back: React.CSSProperties = { minHeight: 48, display: "inline-flex", alignItems: "center", gap: 8, color: "var(--color-gold-800)", textDecoration: "none", marginBottom: 12 }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 24, flexWrap: "wrap" }; const actions: React.CSSProperties = { display: "flex", gap: 10, flexWrap: "wrap" }; const eyebrow: React.CSSProperties = { color: "var(--color-gold-800)", fontSize: 11, fontWeight: 700, letterSpacing: ".08em", margin: "4px 0 8px" }; const title: React.CSSProperties = { fontSize: "clamp(32px,5vw,48px)", fontWeight: 500, margin: 0 }; const emerald: React.CSSProperties = { minHeight: 48, border: 0, borderRadius: 8, padding: "0 18px", display: "inline-flex", gap: 8, alignItems: "center", background: "var(--color-emerald-900)", color: "var(--color-cream-100)", fontWeight: 700 }; const gold: React.CSSProperties = { ...emerald, border: "1px solid var(--color-gold-600)", borderRadius: 12, background: "transparent", color: "var(--color-gold-600)" }; const ghost: React.CSSProperties = { minHeight: 48, border: "1px solid var(--color-cream-500)", borderRadius: 8, padding: "0 18px", display: "inline-flex", gap: 8, alignItems: "center", background: "transparent", color: "var(--color-warm-700)", fontWeight: 700 }; const roomGrid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(230px, 1fr))", gap: 16 }; const empty: React.CSSProperties = { minHeight: 280, display: "grid", placeItems: "center", alignContent: "center", gap: 12, textAlign: "center", padding: 24, border: "1px dashed var(--color-cream-400)", borderRadius: 12, background: "var(--color-cream-100)" };
