"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { accommodationClient } from "@/lib/rpc";

type Props = { open: boolean; hotelId: string; onClose: () => void; onSaved: (count: number) => void };
const capacities: Record<string, number> = { single: 1, double: 2, triple: 3, quadruple: 4 };

export default function BulkRoomDialog({ open, hotelId, onClose, onSaved }: Props) {
  const [form, setForm] = useState({ roomNumbers: "", roomType: "", gender: "", capacity: "", floor: "", notes: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setForm({ roomNumbers: "", roomType: "", gender: "", capacity: "", floor: "", notes: "" }); setError(""); } }, [open]);
  const roomNumbers = useMemo(() => form.roomNumbers.split(/\r?\n/).map((number) => number.trim().toUpperCase()).filter(Boolean), [form.roomNumbers]);
  if (!open) return null;
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (!roomNumbers.length || !form.roomType || !form.gender || Number(form.capacity) < 1) { setError("Isi nomor kamar dan lengkapi semua data yang wajib diisi."); return; } if (new Set(roomNumbers).size !== roomNumbers.length) { setError("Setiap nomor kamar harus unik."); return; } setSaving(true); try { const response = await accommodationClient.bulkCreateRooms({ hotelId, roomNumbers, roomType: form.roomType, gender: form.gender, capacity: Number(form.capacity), floor: Number(form.floor) || 0, notes: form.notes.trim() }); onSaved(response.rooms.length); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Gagal membuat kamar."); } finally { setSaving(false); } }
  return <div role="dialog" aria-modal="true" aria-label="Tambah kamar massal" style={overlay}><aside style={sheet}><header style={header}><div><p style={eyebrow}>PENGATURAN KAMAR MASSAL</p><h2 style={{ margin: 0 }}>Tambah kamar</h2></div><button type="button" onClick={onClose} style={ghost}>Tutup</button></header><div className="gold-divider" /><form onSubmit={submit} style={{ display: "grid", gap: 16 }}><Field label="Nomor kamar" required><textarea required placeholder={"101\n102\n103"} value={form.roomNumbers} onChange={(event) => update("roomNumbers", event.target.value)} style={{ ...input, minHeight: 150, fontFamily: "ui-monospace, monospace" }} /></Field><p role="status" style={{ margin: "-6px 0 0", color: "var(--color-warm-400)", fontSize: 13 }}>{roomNumbers.length} kamar akan dibuat</p><Field label="Tipe kamar" required><select required value={form.roomType} onChange={(event) => setForm((current) => ({ ...current, roomType: event.target.value, capacity: String(capacities[event.target.value] ?? "") }))} style={input}><option value="">Pilih tipe</option>{Object.keys(capacities).map((type) => <option key={type} value={type}>{type.charAt(0).toUpperCase() + type.slice(1)}</option>)}</select></Field><Field label="Jenis Kelamin" required><select required value={form.gender} onChange={(event) => update("gender", event.target.value)} style={input}><option value="">Pilih peruntukan</option>{["male", "female", "family"].map((gender) => <option key={gender} value={gender}>{gender === "male" ? "Pria" : gender === "female" ? "Wanita" : "Keluarga"}</option>)}</select></Field><div style={twoCols}><Field label="Kapasitas" required><input required min="1" type="number" value={form.capacity} onChange={(event) => update("capacity", event.target.value)} style={input} /></Field><Field label="Lantai"><input type="number" value={form.floor} onChange={(event) => update("floor", event.target.value)} style={input} /></Field></div><Field label="Catatan"><input value={form.notes} onChange={(event) => update("notes", event.target.value)} style={input} /></Field>{error && <p role="alert" style={errorStyle}>{error}</p>}<button disabled={saving} style={primary}>{saving ? "Membuat..." : `Buat ${roomNumbers.length || ""} kamar`}</button></form></aside></div>;
}
function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <label style={{ display: "grid", gap: 6, color: "var(--color-warm-500)", fontSize: 14 }}>{label}{required ? " *" : ""}{children}</label>; }
const overlay: React.CSSProperties = { position: "fixed", inset: 0, zIndex: 30, display: "flex", justifyContent: "flex-end", background: "rgba(15,23,42,.52)" }; const sheet: React.CSSProperties = { width: "min(540px,100%)", minHeight: "100%", overflowY: "auto", background: "var(--color-cream-100)", padding: 24, boxShadow: "0 8px 24px rgba(15,23,42,.12)", animation: "sheet-in .2s ease-out" }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "flex-start" }; const eyebrow: React.CSSProperties = { margin: "0 0 6px", color: "var(--color-gold-800)", fontSize: 11, fontWeight: 700, letterSpacing: ".08em" }; const input: React.CSSProperties = { minHeight: 48, width: "100%", border: "1px solid var(--color-cream-500)", borderRadius: 8, padding: "10px 12px", background: "var(--color-cream-200)", color: "#fff", font: "inherit" }; const ghost: React.CSSProperties = { minHeight: 48, border: "1px solid var(--color-cream-500)", borderRadius: 8, background: "transparent", color: "var(--color-warm-500)", padding: "0 16px" }; const primary: React.CSSProperties = { minHeight: 48, border: 0, borderRadius: 8, background: "var(--color-gold-500)", color: "#fff", fontWeight: 700, padding: "0 20px" }; const twoCols: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 12 }; const errorStyle: React.CSSProperties = { margin: 0, color: "var(--color-danger-600)" };
