"use client";

import { useEffect, useMemo, useState } from "react";
import { IconGenderFemale, IconGenderMale, IconSearch, IconUserMinus, IconUserPlus } from "@tabler/icons-react";
import { Gender, Pilgrim } from "@hajj-saas/proto-gen/hajj/v1/pilgrim_pb";
import { Room, RoomManifest } from "@hajj-saas/proto-gen/hajj/v1/accommodation_pb";
import { accommodationClient, pilgrimClient } from "@/lib/rpc";

type Props = { open: boolean; room: Room | null; seasonId: string; allocatedPilgrimIds: Set<string>; onClose: () => void; onChanged: () => void };

export default function RoomAllocationPanel({ open, room, seasonId, allocatedPilgrimIds, onClose, onChanged }: Props) {
  const [manifest, setManifest] = useState<RoomManifest>(); const [pilgrims, setPilgrims] = useState<Pilgrim[]>([]); const [query, setQuery] = useState(""); const [term, setTerm] = useState(""); const [notice, setNotice] = useState(""); const [workingId, setWorkingId] = useState("");
  const roomId = room?.id;
  const refresh = (id = roomId) => { if (!id) return; accommodationClient.getRoomManifest({ roomId: id }).then(setManifest).catch(() => setNotice("Unable to load room occupants.")); };
  useEffect(() => { if (open && roomId) { setNotice(""); setQuery(""); refresh(roomId); pilgrimClient.listPilgrims({ seasonId, limit: 100, offset: 0 }).then((response) => setPilgrims(response.pilgrims)).catch(() => setNotice("Unable to load pilgrims.")); } }, [open, roomId, seasonId]);
  useEffect(() => { const timeout = window.setTimeout(() => setTerm(query), 300); return () => window.clearTimeout(timeout); }, [query]);
  const occupants = manifest?.pilgrims ?? []; const full = !!manifest && manifest.availableCapacity <= 0;
  const candidates = useMemo(() => pilgrims.filter((pilgrim) => !allocatedPilgrimIds.has(pilgrim.id) && !pilgrim.isSubstituted && `${pilgrim.fullName} ${pilgrim.passportNumber}`.toLowerCase().includes(term.toLowerCase())), [allocatedPilgrimIds, pilgrims, term]);
  if (!open || !room || !roomId) return null;
  const activeRoom = room;
  async function remove(pilgrimId: string) { setWorkingId(pilgrimId); setNotice(""); try { await accommodationClient.deallocatePilgrim({ pilgrimId }); refresh(); onChanged(); } catch (caught) { setNotice(caught instanceof Error ? caught.message : "Unable to remove pilgrim."); } finally { setWorkingId(""); } }
  async function assign(pilgrimId: string) { setWorkingId(pilgrimId); setNotice(""); try { await accommodationClient.allocatePilgrim({ roomId, pilgrimId }); refresh(roomId); onChanged(); } catch (caught) { const message = caught instanceof Error ? caught.message : "Unable to assign pilgrim."; if (/capacity|resource_exhausted|full/i.test(message)) setNotice("Room is full"); else if (/designated|gender|failed_precondition/i.test(message)) setNotice(`Gender mismatch - room is ${activeRoom.gender} only`); else setNotice(message); } finally { setWorkingId(""); } }
  return <div role="dialog" aria-modal="true" aria-label={`Allocate room ${room.roomNumber}`} style={overlay}><aside style={sheet}><header style={header}><div><p style={eyebrow}>ROOM ALLOCATION</p><h2 style={{ margin: 0 }}>Room {room.roomNumber}</h2><p style={{ margin: "6px 0 0", color: "var(--color-warm-500)" }}>{label(room.roomType)} · {label(room.gender)} · {room.capacity - (manifest?.availableCapacity ?? room.capacity)}/{room.capacity}</p></div><button type="button" onClick={onClose} style={ghost}>Close</button></header><div className="gold-divider" /><section style={{ display: "grid", gap: 10 }}><h3 style={sectionTitle}>Current occupants</h3>{occupants.length ? occupants.map((pilgrim) => <div key={pilgrim.id} style={person}><div><strong>{pilgrim.fullName}</strong><span style={meta}>{pilgrim.passportNumber} · {pilgrim.gender === Gender.FEMALE ? "Female" : "Male"}</span></div><button disabled={workingId === pilgrim.id} onClick={() => remove(pilgrim.id)} style={removeButton}><IconUserMinus size={17} />Remove</button></div>) : <p style={{ margin: 0, color: "var(--color-warm-400)" }}>No pilgrims assigned yet.</p>}</section>{!full && <section style={{ display: "grid", gap: 12, marginTop: 24 }}><h3 style={sectionTitle}>Assign pilgrim</h3><label style={{ position: "relative" }}><span style={sr}>Search unallocated pilgrims</span><IconSearch size={18} style={{ position: "absolute", insetInlineStart: 14, top: 15, color: "var(--color-warm-400)" }} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or passport" style={{ ...input, paddingInlineStart: 42 }} /></label>{candidates.slice(0, 20).map((pilgrim) => <div key={pilgrim.id} style={person}><div><strong>{pilgrim.fullName}</strong><span style={meta}>{pilgrim.passportNumber} · {pilgrim.gender === Gender.FEMALE ? <IconGenderFemale size={15} /> : <IconGenderMale size={15} />}</span></div><button disabled={workingId === pilgrim.id} onClick={() => assign(pilgrim.id)} style={assignButton}><IconUserPlus size={17} />Assign</button></div>)}{!candidates.length && <p style={{ margin: 0, color: "var(--color-warm-400)" }}>No unallocated pilgrims match this search.</p>}</section>}{full && <p role="status" style={fullNotice}>Room is full</p>}{notice && <p role="status" style={{ color: "var(--color-gold-800)", marginTop: 20 }}>{notice}</p>}</aside></div>;
}
function label(value: string) { return value ? value.charAt(0).toUpperCase() + value.slice(1) : "-"; }
const overlay: React.CSSProperties = { position: "fixed", inset: 0, zIndex: 30, display: "flex", justifyContent: "flex-end", background: "rgba(26,20,16,.52)" }; const sheet: React.CSSProperties = { width: "min(600px,100%)", minHeight: "100%", overflowY: "auto", background: "var(--color-cream-100)", padding: 24, boxShadow: "0 8px 24px rgba(26,20,16,.12)", animation: "sheet-in .2s ease-out" }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "flex-start" }; const eyebrow: React.CSSProperties = { margin: "0 0 6px", color: "var(--color-gold-800)", fontSize: 11, fontWeight: 700, letterSpacing: ".08em" }; const ghost: React.CSSProperties = { minHeight: 48, border: "1px solid var(--color-cream-500)", borderRadius: 8, background: "transparent", color: "var(--color-warm-500)", padding: "0 16px" }; const sectionTitle: React.CSSProperties = { margin: 0, fontSize: 20, fontFamily: "'Playfair Display', serif", color: "var(--color-emerald-900)" }; const person: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, padding: 12, border: "1px solid var(--color-cream-300)", borderRadius: 8, background: "var(white)" }; const meta: React.CSSProperties = { display: "flex", alignItems: "center", gap: 4, marginTop: 3, color: "var(--color-warm-400)", fontFamily: "ui-monospace, monospace", fontSize: 12 }; const removeButton: React.CSSProperties = { minHeight: 48, border: "1px solid var(--color-danger-600)", borderRadius: 8, background: "var(--color-danger-100)", color: "var(--color-danger-600)", padding: "0 12px", display: "inline-flex", alignItems: "center", gap: 6 }; const assignButton: React.CSSProperties = { minHeight: 48, border: 0, borderRadius: 8, background: "var(--color-emerald-900)", color: "var(--color-cream-100)", padding: "0 12px", display: "inline-flex", alignItems: "center", gap: 6 }; const input: React.CSSProperties = { minHeight: 48, width: "100%", border: "1px solid var(--color-cream-500)", borderRadius: 8, padding: "10px 12px", background: "var(--color-cream-200)", color: "var(--color-warm-900)", font: "inherit" }; const fullNotice: React.CSSProperties = { marginTop: 24, padding: 12, borderRadius: 8, background: "var(--color-gold-50)", color: "var(--color-gold-800)" }; const sr: React.CSSProperties = { position: "absolute", width: 1, height: 1, overflow: "hidden", clip: "rect(0 0 0 0)" };
