"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { IconGenderFemale, IconGenderMale, IconSearch, IconUserMinus, IconUserPlus } from "@tabler/icons-react";
import { Gender, Pilgrim } from "@hajj-saas/proto-gen/hajj/v1/pilgrim_pb";
import { Room, RoomManifest } from "@hajj-saas/proto-gen/hajj/v1/accommodation_pb";
import { accommodationClient, pilgrimClient } from "@/lib/rpc";

type Props = { open: boolean; room: Room | null; seasonId: string; allocatedPilgrimIds: Set<string>; onClose: () => void; onChanged: () => void };

export default function RoomAllocationPanel({ open, room, seasonId, allocatedPilgrimIds, onClose, onChanged }: Props) {
  const [manifest, setManifest] = useState<RoomManifest>(); const [pilgrims, setPilgrims] = useState<Pilgrim[]>([]); const [query, setQuery] = useState(""); const [term, setTerm] = useState(""); const [notice, setNotice] = useState(""); const [workingId, setWorkingId] = useState("");
  const roomId = room?.id;
  const refresh = useCallback((id = roomId) => { if (!id) return; accommodationClient.getRoomManifest({ roomId: id }).then(setManifest).catch(() => setNotice("Gagal memuat penghuni kamar.")); }, [roomId]);
  useEffect(() => { if (open && roomId) { setNotice(""); setQuery(""); refresh(roomId); pilgrimClient.listPilgrims({ seasonId, limit: 100, offset: 0 }).then((response) => setPilgrims(response.pilgrims)).catch(() => setNotice("Gagal memuat data jamaah.")); } }, [open, refresh, roomId, seasonId]);
  useEffect(() => { const timeout = window.setTimeout(() => setTerm(query), 300); return () => window.clearTimeout(timeout); }, [query]);
  const occupants = useMemo(() => manifest?.pilgrims ?? [], [manifest]); const full = !!manifest && manifest.availableCapacity <= 0;
  const isMahramSuggested = useCallback((pilgrim: Pilgrim) => occupants.some((occupant) => occupant.id === pilgrim.mahramId || pilgrim.id === occupant.mahramId), [occupants]);
  const mahramWarnings = useMemo(() => occupants.filter((occupant) => occupant.mahramId && !occupants.some((other) => other.id === occupant.mahramId)).map((occupant) => { const mahram = pilgrims.find((p) => p.id === occupant.mahramId); return { occupant, mahramName: mahram?.fullName ?? "pasangan mahram-nya" }; }), [occupants, pilgrims]);
  const candidates = useMemo(() => pilgrims
    .filter((pilgrim) => !allocatedPilgrimIds.has(pilgrim.id) && !pilgrim.isSubstituted && `${pilgrim.fullName} ${pilgrim.passportNumber}`.toLowerCase().includes(term.toLowerCase()))
    .sort((a, b) => Number(isMahramSuggested(b)) - Number(isMahramSuggested(a))), [allocatedPilgrimIds, pilgrims, term, isMahramSuggested]);
  if (!open || !room || !roomId) return null;
  const activeRoom = room;
  async function remove(pilgrimId: string) { setWorkingId(pilgrimId); setNotice(""); try { await accommodationClient.deallocatePilgrim({ pilgrimId, roomId }); refresh(); onChanged(); } catch (caught) { setNotice(caught instanceof Error ? caught.message : "Gagal mengeluarkan jamaah."); } finally { setWorkingId(""); } }
  async function assign(pilgrimId: string) { setWorkingId(pilgrimId); setNotice(""); try { await accommodationClient.allocatePilgrim({ roomId, pilgrimId }); refresh(roomId); onChanged(); } catch (caught) { const message = caught instanceof Error ? caught.message : "Gagal menempatkan jamaah."; if (/capacity|resource_exhausted|full/i.test(message)) setNotice("Kamar sudah penuh"); else if (/designated|gender|failed_precondition/i.test(message)) setNotice(`Jenis kelamin tidak sesuai - kamar ini khusus ${activeRoom.gender}`); else setNotice(message); } finally { setWorkingId(""); } }
  return <div role="dialog" aria-modal="true" aria-label={`Kelola kamar ${room.roomNumber}`} style={overlay}><aside style={sheet}><header style={header}><div><p style={eyebrow}>PENEMPATAN KAMAR</p><h2 style={{ margin: 0 }}>Kamar {room.roomNumber}</h2><p style={{ margin: "6px 0 0", color: "var(--color-warm-500)" }}>{ROOM_TYPE_LABEL[room.roomType] ?? label(room.roomType)} · {label(room.gender)} · {room.capacity - (manifest?.availableCapacity ?? room.capacity)}/{room.capacity} terisi</p></div><button type="button" onClick={onClose} style={ghost}>Tutup</button></header><div className="gold-divider" />{mahramWarnings.length > 0 && <div style={{ display: "grid", gap: 6, marginBottom: 12 }}>{mahramWarnings.map(({ occupant, mahramName }) => <p key={occupant.id} role="status" style={mahramWarning}>Peringatan: {occupant.fullName} memiliki pasangan mahram ({mahramName}) yang tidak berada di kamar ini.</p>)}</div>}<section style={{ display: "grid", gap: 10 }}><h3 style={sectionTitle}>Penghuni saat ini</h3>{occupants.length ? occupants.map((pilgrim) => <div key={pilgrim.id} style={person}><div><strong>{pilgrim.fullName}</strong><span style={meta}>{pilgrim.passportNumber} · {pilgrim.gender === Gender.FEMALE ? "Wanita" : "Pria"}</span></div><button disabled={workingId === pilgrim.id} onClick={() => remove(pilgrim.id)} style={removeButton}><IconUserMinus size={17} />Keluarkan</button></div>) : <p style={{ margin: 0, color: "var(--color-warm-400)" }}>Belum ada jamaah yang ditempatkan.</p>}</section>{!full && <section style={{ display: "grid", gap: 12, marginTop: 24 }}><h3 style={sectionTitle}>Tempatkan jamaah</h3><label style={{ position: "relative" }}><span style={sr}>Cari jamaah yang belum ditempatkan</span><IconSearch size={18} style={{ position: "absolute", insetInlineStart: 14, top: 15, color: "var(--color-warm-400)" }} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama jamaah atau nomor paspor…" style={{ ...input, paddingInlineStart: 42 }} /></label>{candidates.slice(0, 20).map((pilgrim) => <div key={pilgrim.id} style={person}><div><strong>{pilgrim.fullName}</strong>{isMahramSuggested(pilgrim) && <span style={mahramBadge}>Disarankan · pasangan mahram</span>}<span style={meta}>{pilgrim.passportNumber} · {pilgrim.gender === Gender.FEMALE ? <IconGenderFemale size={15} /> : <IconGenderMale size={15} />}</span></div><button disabled={workingId === pilgrim.id} onClick={() => assign(pilgrim.id)} style={assignButton}><IconUserPlus size={17} />Tempatkan</button></div>)}{!candidates.length && <p style={{ margin: 0, color: "var(--color-warm-400)" }}>Tidak ada jamaah yang cocok dengan pencarian ini.</p>}</section>}{full && <p role="status" style={fullNotice}>Kamar sudah penuh</p>}{notice && <p role="status" style={{ color: "var(--color-gold-800)", marginTop: 20 }}>{notice}</p>}</aside></div>;
}
function label(value: string) { return value ? value.charAt(0).toUpperCase() + value.slice(1) : "-"; }
const ROOM_TYPE_LABEL: Record<string, string> = { single: "Single", double: "Double", triple: "Triple", quad: "Quadruple", quadruple: "Quadruple" };
const overlay: React.CSSProperties = { position: "fixed", inset: 0, zIndex: 30, display: "flex", justifyContent: "flex-end", background: "rgba(15,23,42,.52)" }; const sheet: React.CSSProperties = { width: "min(600px,100%)", minHeight: "100%", overflowY: "auto", background: "var(--color-cream-100)", padding: 24, boxShadow: "0 8px 24px rgba(15,23,42,.12)", animation: "sheet-in .2s ease-out" }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "flex-start" }; const eyebrow: React.CSSProperties = { margin: "0 0 6px", color: "var(--color-gold-800)", fontSize: 11, fontWeight: 700, letterSpacing: ".08em" }; const ghost: React.CSSProperties = { minHeight: 48, border: "1px solid var(--color-cream-500)", borderRadius: 8, background: "transparent", color: "var(--color-warm-500)", padding: "0 16px" }; const sectionTitle: React.CSSProperties = { margin: 0, fontSize: 20, fontFamily: "'Playfair Display', serif", color: "var(--color-emerald-900)" }; const person: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, padding: 12, border: "1px solid var(--color-cream-300)", borderRadius: 8, background: "var(white)" }; const meta: React.CSSProperties = { display: "flex", alignItems: "center", gap: 4, marginTop: 3, color: "var(--color-warm-400)", fontFamily: "ui-monospace, monospace", fontSize: 12 }; const removeButton: React.CSSProperties = { minHeight: 48, border: "1px solid var(--color-danger-600)", borderRadius: 8, background: "var(--color-danger-100)", color: "var(--color-danger-600)", padding: "0 12px", display: "inline-flex", alignItems: "center", gap: 6 }; const assignButton: React.CSSProperties = { minHeight: 48, border: 0, borderRadius: 8, background: "var(--color-emerald-900)", color: "var(--color-cream-100)", padding: "0 12px", display: "inline-flex", alignItems: "center", gap: 6 }; const input: React.CSSProperties = { minHeight: 48, width: "100%", border: "1px solid var(--color-cream-500)", borderRadius: 8, padding: "10px 12px", background: "var(--color-cream-200)", color: "var(--color-warm-900)", font: "inherit" }; const fullNotice: React.CSSProperties = { marginTop: 24, padding: 12, borderRadius: 8, background: "var(--color-gold-50)", color: "var(--color-gold-800)" }; const mahramBadge: React.CSSProperties = { display: "inline-block", marginInlineStart: 8, padding: "2px 7px", borderRadius: 99, background: "var(--color-gold-50)", color: "var(--color-gold-800)", fontSize: 11, fontWeight: 700 };
const mahramWarning: React.CSSProperties = { margin: 0, padding: "10px 14px", borderRadius: 8, background: "var(--color-danger-100)", color: "var(--color-danger-600)", fontSize: 13, fontWeight: 600 }; const sr: React.CSSProperties = { position: "absolute", width: 1, height: 1, overflow: "hidden", clip: "rect(0 0 0 0)" };
