"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { IconBuildingHospital, IconBus, IconFileAnalytics, IconLayoutDashboard, IconLogout, IconMenu2, IconSettings, IconShoppingCart, IconUserDollar, IconUsers } from "@tabler/icons-react";
import { authClient } from "@/lib/auth-client";
import { operatorClient, seasonClient } from "@/lib/rpc";

const nav = [["Overview", "/dashboard", IconLayoutDashboard], ["Pilgrims", "/dashboard/pilgrims", IconUsers], ["Accommodation", "/dashboard/accommodation", IconBuildingHospital], ["Transport", "/dashboard/transport", IconBus], ["Products", "/dashboard/products", IconShoppingCart], ["Agents", "/dashboard/agents", IconUserDollar], ["Reports", "/dashboard/reports", IconFileAnalytics]] as const;

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const { data: session } = authClient.useSession(); const [open, setOpen] = useState(false); const [operator, setOperator] = useState(""); const [season, setSeason] = useState("");
  useEffect(() => { operatorClient.getMyOperator({}).then((value) => setOperator(value.name)).catch(async (err) => { if (err?.code === "unauthenticated") { await authClient.getSession({ fetchOptions: { cache: "no-store" } }); operatorClient.getMyOperator({}).then((value) => setOperator(value.name)).catch(() => router.push("/sign-in")); } }); seasonClient.listSeasons({}).then((value) => setSeason((value.seasons.find((item) => item.isActive) ?? value.seasons[0])?.name ?? "")).catch(async (err) => { if (err?.code === "unauthenticated") { await authClient.getSession({ fetchOptions: { cache: "no-store" } }); seasonClient.listSeasons({}).then((value) => setSeason((value.seasons.find((item) => item.isActive) ?? value.seasons[0])?.name ?? "")).catch(() => router.push("/sign-in")); } }); }, [router]);
  async function signOut() { await authClient.signOut(); router.push("/sign-in"); }
  const sidebarNode = <nav style={sidebarStyle}><div style={brand}><Link href="/" aria-label="Safrat home" style={logo}>Safrat</Link>{operator && <p style={org}>{operator}</p>}{season && <p style={seasonStyle}><i style={dot} />{season}</p>}</div><div className="gold-divider" style={{ margin: "0 16px 8px" }} /><ul style={list}>{nav.map(([label, href, Icon]) => { const active = pathname === href || (href !== "/dashboard" && pathname.startsWith(href)); return <li key={href}><Link href={href} onClick={() => setOpen(false)} style={{ ...item, ...(active ? activeItem : {}) }}><Icon size={18} />{label}{active && <i style={activeDot} />}</Link></li>; })}</ul><div style={bottom}><div className="gold-divider" /><span style={disabled}><IconSettings size={18} />Settings<b style={soon}>Soon</b></span><p style={email}>{session?.user?.email}</p><button className="btn-signout" onClick={() => void signOut()} style={signOutStyle}><IconLogout size={16} />Sign out</button></div></nav>;
  return <div style={shell}><aside data-desktop-sidebar style={desktop}>{sidebarNode}</aside>{open && <div style={overlay} onClick={() => setOpen(false)}><div style={mobile} onClick={(event) => event.stopPropagation()}>{sidebarNode}</div></div>}<div style={content}><header data-mobile-header="" style={mobileHeader}><button aria-label="Open menu" onClick={() => setOpen(true)} style={menu}><IconMenu2 size={22} /></button><div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 1 }}><Link href="/" onClick={() => setOpen(false)} aria-label="Safrat home" style={{ ...logo, fontSize: 18, lineHeight: 1 }}>Safrat</Link>{season && <span style={{ fontSize: 10, color: "rgba(255,255,255,0.55)", letterSpacing: "0.06em", fontFamily: "'Plus Jakarta Sans', sans-serif", fontWeight: 500 }}>{season}</span>}</div><div style={{ width: 40 }} /></header>{children}</div></div>;
}
const width=240; const shell:React.CSSProperties={display:"flex",minHeight:"100vh"}; const sidebarStyle:React.CSSProperties={width,minHeight:"100vh",background:"var(--color-emerald-900)",display:"flex",flexDirection:"column",paddingTop:24}; const desktop:React.CSSProperties={width,flexShrink:0,position:"sticky",top:0,height:"100vh",display:"none"}; const content:React.CSSProperties={flex:1,minWidth:0}; const overlay:React.CSSProperties={position:"fixed",inset:0,zIndex:50,background:"rgba(0,0,0,.5)"}; const mobile:React.CSSProperties={width,height:"100vh",overflowY:"auto"}; const mobileHeader: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 16px", background: "rgba(13,61,39,0.92)", backdropFilter: "blur(12px)", WebkitBackdropFilter: "blur(12px)", position: "sticky", top: 0, zIndex: 40, borderBottom: "1px solid rgba(201,168,76,0.20)" }; const menu: React.CSSProperties = { width: 40, height: 40, border: "1px solid rgba(201,168,76,0.25)", borderRadius: 10, background: "rgba(255,255,255,0.06)", color: "var(--color-cream-100)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }; const brand:React.CSSProperties={padding:"0 20px 16px"}; const logo:React.CSSProperties={fontFamily:"'Playfair Display', Georgia, serif",color:"var(--color-gold-500)",fontSize:28,fontWeight:700}; const org:React.CSSProperties={color:"var(--color-cream-100)",fontSize:13,margin:"8px 0 4px",fontWeight:600}; const seasonStyle:React.CSSProperties={margin:0,color:"rgba(255,255,255,.6)",fontSize:12,display:"flex",alignItems:"center",gap:6}; const dot:React.CSSProperties={width:6,height:6,borderRadius:"50%",background:"var(--color-gold-500)"}; const list:React.CSSProperties={listStyle:"none",margin:0,padding:0,flex:1}; const item:React.CSSProperties={minHeight:48,display:"flex",alignItems:"center",gap:12,padding:"12px 20px",color:"rgba(255,255,255,.7)",fontSize:14,position:"relative"}; const activeItem:React.CSSProperties={color:"var(--color-cream-100)",fontWeight:700,background:"rgba(255,255,255,.08)",borderLeft:"3px solid var(--color-gold-500)",padding:"12px 20px 12px 17px"}; const disabled:React.CSSProperties={...item,color:"rgba(255,255,255,.3)"}; const activeDot:React.CSSProperties={width:6,height:6,borderRadius:"50%",background:"var(--color-gold-500)",marginLeft:"auto"}; const soon:React.CSSProperties={marginLeft:"auto",fontSize:10,color:"rgba(255,255,255,.4)",border:"1px solid rgba(255,255,255,.2)",borderRadius:4,padding:"1px 5px"}; const bottom:React.CSSProperties={padding:"8px 20px 24px"}; const email:React.CSSProperties={color:"rgba(255,255,255,.5)",fontSize:12,margin:"16px 0 8px"}; const signOutStyle:React.CSSProperties={minHeight:40,border:0,background:"transparent",color:"rgba(255,255,255,.5)",display:"flex",alignItems:"center",gap:8};
