"use client";
import { useEffect, useState } from "react";
import { ConnectError } from "@connectrpc/connect";
import { IconBuildingCommunity, IconChartBar, IconUsers } from "@tabler/icons-react";
import { branchClient, seasonClient } from "@/lib/rpc";
import type { BranchPerformance } from "@hajj-saas/proto-gen/hajj/v1/branch_pb";

const rupiah=(n:bigint|number)=>"Rp"+Number(n).toLocaleString("id-ID");
export default function BranchPage(){const [rows,setRows]=useState<BranchPerformance[]>([]);const [error,setError]=useState("");useEffect(()=>{void (async()=>{try{const seasons=await seasonClient.listSeasons({});const season=seasons.seasons.find(x=>x.isActive)??seasons.seasons[0];if(!season){setError("Buat musim aktif terlebih dahulu agar kinerja cabang dapat dihitung.");return}const report=await branchClient.getBranchPerformance({seasonId:season.id});setRows(report.branches)}catch(e){setError(ConnectError.from(e).rawMessage)}})()},[]);return <main className="dashboard-page"><header className="dashboard-page-header"><div><p className="dashboard-eyebrow">JARINGAN CABANG</p><h1>Cabang</h1><p>Target, realisasi, dan kesiapan operasional setiap cabang.</p></div></header>{error?<p className="dashboard-inline-error">{error}</p>:rows.length===0?<section className="tw-card dashboard-empty"><IconBuildingCommunity size={28}/><h2>Belum ada cabang aktif</h2><p>Tambahkan cabang pertama untuk membandingkan target, omzet, dan kesiapan dokumen.</p></section>:<section className="tw-card"><div className="branch-table" role="table"><div className="branch-row branch-head" role="row"><span>Cabang</span><span>Omzet</span><span>Jamaah</span><span>Agen</span><span>Skor</span></div>{rows.map(r=><div className="branch-row" role="row" key={r.branch?.id}><strong><IconBuildingCommunity size={17}/>{r.branch?.name}<small>{r.branch?.city}</small></strong><span><IconChartBar size={16}/>{rupiah(r.revenueIdr)}</span><span><IconUsers size={16}/>{r.pilgrimCount} / {r.branch?.targetPilgrims||"—"}</span><span>{r.agentCount}</span><span className="branch-score">{r.score.toFixed(1)}</span></div>)}</div></section>}</main>}
