"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { authClient } from "@/lib/auth-client";
type Mode="sign-in"|"sign-up";
export function AuthForm({mode}:{mode:Mode}) { const router=useRouter(); const [error,setError]=useState<string|null>(null); const [isSubmitting,setSubmitting]=useState(false); const [focused,setFocused]=useState(""); const signUp=mode==="sign-up";
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(null);setSubmitting(true);try{const form=new FormData(event.currentTarget);const result=signUp?await authClient.signUp.email({name:String(form.get("name")??""),email:String(form.get("email")??""),password:String(form.get("password")??"")}):await authClient.signIn.email({email:String(form.get("email")??""),password:String(form.get("password")??"")});if(result.error){setError(result.error.message??(signUp?"Could not create your account.":"Could not sign in."));return;}const session=await authClient.getSession({fetchOptions:{cache:"no-store"}});if(!session.data?.user){setError("Your session could not be confirmed. Please try again.");return;}const orgList=await authClient.organization.list();const firstOrganization=orgList.data?.[0];if(!signUp&&firstOrganization&&!session.data.session?.activeOrganizationId){await authClient.organization.setActive({organizationId:firstOrganization.id});await authClient.getSession({fetchOptions:{cache:"no-store"}});}router.replace(signUp||!firstOrganization?"/onboarding":"/dashboard");}catch{setError("Unable to complete sign in. Please try again.");}finally{setSubmitting(false);}}
 const input=(name:string,type="text")=><input name={name} type={type} required minLength={name==="password"?8:undefined} style={{...inputStyle,borderWidth:1,borderStyle:"solid",borderColor:focused===name?"var(--color-emerald-800)":"var(--color-cream-500)"}} onFocus={()=>setFocused(name)} onBlur={()=>setFocused("")} />;
 return <form onSubmit={submit} style={{display:"grid",gap:16}}>{signUp&&<label style={labelStyle}>Name{input("name")}</label>}<label style={labelStyle}>Email{input("email","email")}</label><label style={labelStyle}>Password{input("password","password")}</label>{error&&<p role="alert" style={{color:"var(--color-danger-600)",fontSize:13}}>{error}</p>}<button type="submit" disabled={isSubmitting} style={submitStyle}>{isSubmitting?"Please wait...":signUp?"Create account":"Sign in"}</button></form>; }
const labelStyle:React.CSSProperties={display:"block",fontSize:13,fontWeight:600,color:"var(--color-warm-700)"}; const inputStyle:React.CSSProperties={display:"block",width:"100%",marginTop:6,padding:"10px 12px",fontSize:14,borderRadius:8,background:"var(--color-cream-200)",fontFamily:"'Plus Jakarta Sans',sans-serif",outline:"none"}; const submitStyle:React.CSSProperties={width:"100%",height:44,background:"var(--color-gold-500)",color:"var(--color-warm-900)",border:"none",borderRadius:8,fontSize:14,fontWeight:700,cursor:"pointer",fontFamily:"'Plus Jakarta Sans',sans-serif",marginTop:8};
