"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { authClient } from "@/lib/auth-client";
import { resolveLandingPath } from "@/lib/post-login";
import { GoogleSignInButton } from "@/components/auth/GoogleSignInButton";
type Mode="sign-in"|"sign-up";
export function AuthForm({mode}:{mode:Mode}) { const router=useRouter(); const [error,setError]=useState<string|null>(null); const [isSubmitting,setSubmitting]=useState(false); const [focused,setFocused]=useState(""); const signUp=mode==="sign-up";
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(null);setSubmitting(true);try{const form=new FormData(event.currentTarget);const result=signUp?await authClient.signUp.email({name:String(form.get("name")??""),email:String(form.get("email")??""),password:String(form.get("password")??"")}):await authClient.signIn.email({email:String(form.get("email")??""),password:String(form.get("password")??"")});if(result.error){setError(result.error.message??(signUp?"Gagal membuat akun Anda.":"Gagal masuk."));return;}const session=await authClient.getSession({fetchOptions:{cache:"no-store"}});if(!session.data?.user){setError("Sesi Anda tidak dapat dikonfirmasi. Silakan coba lagi.");return;}const path=signUp?"/onboarding":await resolveLandingPath();router.replace(path);}catch{setError("Gagal menyelesaikan proses masuk. Silakan coba lagi.");}finally{setSubmitting(false);}}
 const input=(name:string,type="text")=><input name={name} type={type} required minLength={name==="password"?8:undefined} style={{...inputStyle,borderWidth:1,borderStyle:"solid",borderColor:focused===name?"var(--color-emerald-800)":"var(--color-cream-500)"}} onFocus={()=>setFocused(name)} onBlur={()=>setFocused("")} />;
 return <div style={{display:"grid",gap:16}}><form onSubmit={submit} style={{display:"grid",gap:16}}>{signUp&&<label style={labelStyle}>Nama{input("name")}</label>}<label style={labelStyle}>Email{input("email","email")}</label><label style={labelStyle}>Kata Sandi{input("password","password")}</label>{error&&<p role="alert" style={{color:"var(--color-danger-600)",fontSize:13}}>{error}</p>}<button type="submit" disabled={isSubmitting} style={submitStyle}>{isSubmitting?"Mohon tunggu...":signUp?"Buat akun":"Masuk"}</button></form><div style={{display:"flex",alignItems:"center",gap:10,color:"var(--color-warm-400)",fontSize:12}}><div style={{flex:1,height:1,background:"var(--color-cream-400)"}}/>atau<div style={{flex:1,height:1,background:"var(--color-cream-400)"}}/></div><GoogleSignInButton callbackURL="/sign-in" /></div>; }
const labelStyle:React.CSSProperties={display:"block",fontSize:13,fontWeight:600,color:"var(--color-warm-700)"}; const inputStyle:React.CSSProperties={display:"block",width:"100%",marginTop:6,padding:"10px 12px",fontSize:14,borderRadius:8,background:"var(--color-cream-200)",fontFamily:"'Plus Jakarta Sans',sans-serif",outline:"none"}; const submitStyle:React.CSSProperties={width:"100%",height:44,background:"var(--color-gold-500)",color:"var(--color-warm-900)",border:"none",borderRadius:8,fontSize:14,fontWeight:700,cursor:"pointer",fontFamily:"'Plus Jakarta Sans',sans-serif",marginTop:8};
