"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { authClient } from "@/lib/auth-client";
import { resolveLandingPath } from "@/lib/post-login";
import { GoogleSignInButton } from "@/components/auth/GoogleSignInButton";
type Mode="sign-in"|"sign-up";
export function AuthForm({mode}:{mode:Mode}) { const router=useRouter(); const [error,setError]=useState<string|null>(null); const [isSubmitting,setSubmitting]=useState(false); const [focused,setFocused]=useState(""); const [checkEmail,setCheckEmail]=useState<string|null>(null); const [unverifiedEmail,setUnverifiedEmail]=useState<string|null>(null); const [resending,setResending]=useState(false); const signUp=mode==="sign-up";
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(null);setUnverifiedEmail(null);setSubmitting(true);try{const form=new FormData(event.currentTarget);const email=String(form.get("email")??"");const result=signUp?await authClient.signUp.email({name:String(form.get("name")??""),email,password:String(form.get("password")??"")}):await authClient.signIn.email({email,password:String(form.get("password")??"")});if(result.error){if(result.error.code==="EMAIL_NOT_VERIFIED"){setUnverifiedEmail(email);setError("Email Anda belum diverifikasi. Periksa kotak masuk Anda, atau kirim ulang di bawah.");}else{setError(result.error.message??(signUp?"Gagal membuat akun Anda.":"Gagal masuk."));}return;}
  // requireEmailVerification means sign-up never establishes a session —
  // there's nothing to redirect to yet, just tell them to check their inbox.
  if(signUp){setCheckEmail(email);return;}
  const session=await authClient.getSession({fetchOptions:{cache:"no-store"}});if(!session.data?.user){setError("Sesi Anda tidak dapat dikonfirmasi. Silakan coba lagi.");return;}const path=await resolveLandingPath();router.replace(path);}catch{setError("Gagal menyelesaikan proses masuk. Silakan coba lagi.");}finally{setSubmitting(false);}}
 async function resendVerification(){if(!unverifiedEmail||resending)return;setResending(true);try{await authClient.sendVerificationEmail({email:unverifiedEmail,callbackURL:"/sign-in"});setError("Email verifikasi baru telah dikirim.");}catch{setError("Gagal mengirim ulang email verifikasi.");}finally{setResending(false);}}
 const input=(name:string,type="text")=><input name={name} type={type} required minLength={name==="password"?8:undefined} style={{...inputStyle,borderWidth:1,borderStyle:"solid",borderColor:focused===name?"var(--color-emerald-800)":"var(--color-cream-500)"}} onFocus={()=>setFocused(name)} onBlur={()=>setFocused("")} />;
 if(checkEmail){return <div style={{display:"grid",gap:10,textAlign:"center",padding:"12px 0"}}><p style={{fontWeight:700,fontSize:15}}>Periksa email Anda</p><p style={{fontSize:13,color:"var(--color-warm-500)"}}>Kami mengirim tautan verifikasi ke <strong>{checkEmail}</strong>. Klik tautan tersebut untuk mengaktifkan akun Anda.</p></div>;}
 return <div style={{display:"grid",gap:16}}><form onSubmit={submit} style={{display:"grid",gap:16}}>{signUp&&<label style={labelStyle}>Nama{input("name")}</label>}<label style={labelStyle}>Email{input("email","email")}</label><label style={labelStyle}>Kata Sandi{input("password","password")}</label>{!signUp&&<a href="/forgot-password" style={{fontSize:12,color:"var(--color-emerald-900)",fontWeight:600,justifySelf:"end",marginTop:-8}}>Lupa kata sandi?</a>}{error&&<p role="alert" style={{color:"var(--color-danger-600)",fontSize:13}}>{error}</p>}{unverifiedEmail&&<button type="button" onClick={()=>void resendVerification()} disabled={resending} style={{...submitStyle,background:"transparent",border:"1px solid var(--color-emerald-800)",color:"var(--color-emerald-900)",marginTop:0}}>{resending?"Mengirim...":"Kirim ulang email verifikasi"}</button>}<button type="submit" disabled={isSubmitting} style={submitStyle}>{isSubmitting?"Mohon tunggu...":signUp?"Buat akun":"Masuk"}</button></form><div style={{display:"flex",alignItems:"center",gap:10,color:"var(--color-warm-400)",fontSize:12}}><div style={{flex:1,height:1,background:"var(--color-cream-400)"}}/>atau<div style={{flex:1,height:1,background:"var(--color-cream-400)"}}/></div><GoogleSignInButton callbackURL="/sign-in" /></div>; }
const labelStyle:React.CSSProperties={display:"block",fontSize:13,fontWeight:600,color:"var(--color-warm-700)"}; const inputStyle:React.CSSProperties={display:"block",width:"100%",marginTop:6,padding:"10px 12px",fontSize:14,borderRadius:8,background:"var(--color-cream-200)",fontFamily:"'Plus Jakarta Sans',sans-serif",outline:"none"}; const submitStyle:React.CSSProperties={width:"100%",height:44,background:"var(--color-gold-500)",color:"var(--color-warm-900)",border:"none",borderRadius:8,fontSize:14,fontWeight:700,cursor:"pointer",fontFamily:"'Plus Jakarta Sans',sans-serif",marginTop:8};
